### ISSUE TITLE
Storage API endpoint

### ISSUE THREAD

**Issue by jcnelson** [blockstack/blockstack-registrar#62]
Add an API endpoint that will allow a client to upload their zonefile and profile information.  The endpoint should verify that the zonefile's hash is already present in the blockchain, and that the profile is signed by the key indicated in the zonefile.  This effectively makes the registrar a storage provider for the client.

**Comment by muneeb-ali** [comment]
Issue moved to [blockstack/blockstack-cli #140](https://github.com/blockstack/blockstack-cli/issues/140) via [**ZenHub**](https://www.zenhub.com/)
